image_root: '/mnt/data/datasets/coco/coco2014/'
ann_root: '/data1/yangzhenbang/datasets/blip_caption/data_knowledge'
dataset: 'coco_knowledge'
start_epoch: 0
# set pretrained as a file path or an url
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'
#pretrained: '/mnt/data/yangzhenbang/BLIP/output/Pretrain_knowledge_new/checkpoint_09.pth'
#pretrained: '/mnt/data/yangzhenbang/BLIP/output/Pretrain_knowledge_unfix/checkpoint_01.pth'
#pretrained: '/mnt/data/yangzhenbang/BLIP/output/pretrain_knowledge_new/checkpoint_02.pth'
#pretrained: '/data1/yangzhenbang/BLIP/output/retrieval_coco_knowledge_lora/checkpoint_best.pth'

# size of vit model; base or large

vit: 'base'
#batch_size_train: 16
#batch_size_test: 16
batch_size_train: 24
batch_size_test: 24
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

#vit: 'large'
#batch_size_train: 16
#batch_size_test: 16
#vit_grad_ckpt: True
#vit_ckpt_layer: 12
#init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

#knowledge
sample_rate: 0.5

