image_root: '/mnt/data/datasets/flickr30k'
ann_root: '/mnt/data/yangzhenbang/datasets/blip_caption/data_coco_vg_flickr/kg_data'
dataset: 'flickr_knowledge'

# set pretrained as a file path or an url
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_flickr.pth'
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth'
#pretrained: '/mnt/data/yangzhenbang/BLIP/output/Pretrain_knowledge_unfix/checkpoint_01.pth'
#pretrained: '/mnt/data/yangzhenbang/BLIP/output/Pretrain_knowledge_new/checkpoint_08.pth'
pretrained: '/mnt/data/yangzhenbang/BLIP/output/Pretrain/checkpoint_09.pth'
# size of vit model; base or large

vit: 'base'
#batch_size_train: 32
#batch_size_test: 64
batch_size_train: 4
batch_size_test: 32
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 10
# init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
#k_test: 128
k_test: 128
negative_all_rank: False

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

#knowledge
sample_rate: 0.5